
name: Build Electron App

on:
  push

jobs:
  release:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
      - name: npm install
        run: |
          cd HKMM-UI
          npm install
      - name: Build
        run: |
          cd HKMM-UI
          npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "HKMM-UI/dist_electron/*.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: setup
          path: "HKMM-UI/dist_electron/*.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload unpacked
        uses: actions/upload-artifact@v3
        with:
          name: setup
          path: "HKMM-UI/dist_electron/win-unpacked"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      