
name: Build Electron App

on:
  push

jobs:
  release:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
      - name: Work Dir
        run: |
          cd HKMM-UI
      - name: npm install
        run: |
          npm install
      - name: Build
        run: |
          npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist_electron/*.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}